export const productData = [
  {
    category: "Meat, poultry & deli",
    id: Date.now(),
    name: "Falukorv Ring",
    brand: "Scan",
    description: "800 g",
    sale: { saleMessage: "Sale!" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1742310146/cloud/455592/Falukorv%20Ring.jpg",
    localProduced: true,
    link: "https://www.coop.se/handla/varor/kott-fagel-chark/korv/falukorv/falukorv-ring-7300206787006",
    salePrice: 35,
    price: 42,
    shortExpiryDate: false
  },
  {
    category: "Meat, poultry & deli",
    id: Date.now(),
    name: "Pie Cheese & Ham",
    brand: "Felix",
    description: "220 g, fryst",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1722929387/cloud/376071/Paj%20Ost%20%26%20skinka.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/frys/fardigt-att-varma/paj/paj-ost-skinka-7310240079555",
    price: 31.95,
    shortExpiryDate: false
  },
  {
    category: "Frozen",
    id: Date.now(),
    name: "Pizza X-Tra Allt Capricciosa",
    brand: "Grandiosa",
    description: "350 g, fryst",
    sale: { saleMessage: "Sale!" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1713176338/cloud/344585/Pizza%20X-Tra%20Allt%20Capricciosa.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/frys/fardigt-att-varma/pizza/pizza-x-tra-allt-capricciosa-7310240071672",
    salePrice: 69,
    price: 85,
    shortExpiryDate: false
  },
  {
    category: "Beverages",
    id: Date.now(),
    name: "7up Sugar Free",
    brand: "7up",
    description: "150 cl",
    sale: { saleMessage: "3 for 2" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1694676808/cloud/290598/7up%20Sockerfri.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/dryck/lask/citron-limesmak/7up-sockerfri-7310070004680",
    salePrice: 50,
    shortExpiryDate: false
  },
  {
    category: "Beverages",
    id: Date.now(),
    name: "Pommac Magnum",
    brand: "Pommac",
    description: "10 cl",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1530117881/309118/Pommac%20Magnum.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/dryck/lask/ovriga-smaker/pommac-magnum-7391001000285",
    price: 59.95,
    shortExpiryDate: false
  },
  {
    category: "Beverages",
    id: Date.now(),
    name: "Zingo Zero Orange 6-pack",
    brand: "Zingo",
    description: "6x33 cl.",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1724328533/cloud/380145/Zingo%20Zero%20Apelsin%206-pack.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/dryck/lask/apelsinsmak/zingo-zero-apelsin-6-pack-7310072000765/",
    price: 46.95,
    shortExpiryDate: false
  },
  {
    category: "Beverages",
    id: Date.now(),
    name: "Pepsi Max",
    brand: "Pepsi",
    description: "1,5 liter",
    sale: { saleMessage: "3 for 2" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1710775305/cloud/337339/Pepsi%20Max.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/dryck/lask/cola/pepsi-max-7310072000635",
    price: 50,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Whipping Cream 36%",
    brand: "Arla Köket",
    description: "5 dl",
    sale: { saleMessage: "30 kr/st" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1652099655/cloud/251745/Vispgr%C3%A4dde%2036%25.jpg",
    localProduced: true,
    link: "https://www.coop.se/handla/varor/mejeri-agg/gradde/vispgradde/vispgradde-36-7310865061935",
    salePrice: 30,
    price: 36.5,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Blue Cheese Ädel 30%",
    brand: "Kvibille",
    description: "140 g",
    sale: { saleMessage: "Sale!" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1763117136/cloud/554357/%C3%84delost.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/ost/palaggsost/mjukost/adelost-7311440016364/",
    price: 37,
    salePrice: 37 * 0.7,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Porridge Bread",
    brand: "Pågen",
    description: "780 g",
    sale: { saleMessage: "30% off" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1661934051/cloud/258029/Gr%C3%B6tbr%C3%B6d.jpg",
    localProduced: true,
    link: "https://www.coop.se/handla/varor/morkt-grovt-brod-matbrod/grotbrod-7311070008708",
    salePrice: 34 * 0.7,
    price: 34,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Semi-skimmed Milk",
    brand: "Arla",
    description: "1,5 lit",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206868/cloud/549377/Mellanmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/mejeri-agg/mjolk/mellanmjolk/mellanmjolk-farsk-7310865001825/",
    price: 17,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Semi-skimmed Milk",
    brand: "Arla",
    description: "1,5 lit",
    sale: { saleMessage: "30% off" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206868/cloud/549377/Mellanmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/mejeri-agg/mjolk/mellanmjolk/mellanmjolk-farsk-7310865001825/",
    salePrice: 17 * 0.7,
    price: 17,
    shortExpiryDate: true
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Whole Milk",
    brand: "Arla",
    description: "1,5 lit",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206690/cloud/549370/Standardmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/mejeri-agg/mjolk/standardmjolk/standardmjolk-farsk-7310865000361/",
    price: 20.95,
    shortExpiryDate: false
  },
  {
    category: "Pantry",
    id: Date.now(),
    name: "Granola Hazelnuts & Dates",
    brand: "Paulúns",
    description: "450 g",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1617885984/426809/Granola%20Hasseln%C3%B6tter%20%26%20dadlar.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/skafferi/flingor-musli/granola-crunch/granola-hasselnotter-dadlar-7310240001761/",
    price: 55.95,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Eggs 12-pack M/L Organic",
    brand: "Änglamark",
    description: "12 st",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206690/cloud/549370/Standardmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: true,
    link: "https://www.coop.se/handla/varor/mejeri-agg/egg/egg-12-pack-m-l-eko-7310865061622/",
    price: 51.95,
    shortExpiryDate: false
  },
  {
    category: "Dairy & eggs",
    id: Date.now(),
    name: "Eggs 12-pack M/L Organic",
    brand: "Änglamark",
    description: "12 st",
    sale: { saleMessage: "30% off" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206690/cloud/549370/Standardmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: true,
    link: "https://www.coop.se/handla/varor/mejeri-agg/egg/egg-12-pack-m-l-eko-7310865061622/",
    salePrice: 51.95 * 0.7,
    price: 51.95,
    shortExpiryDate: true
  },
  {
    category: "Coffee",
    id: Date.now(),
    name: "Brewed Coffee Medium Roast",
    brand: "Löfbergs",
    description: "450 g",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1762206690/cloud/549370/Standardmj%C3%B6lk%20F%C3%A4rsk.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/mejeri-agg/egg/egg-12-pack-m-l-eko-7310865061622/",
    price: 69.95,
    shortExpiryDate: false
  },
  {
    category: "Coffee",
    id: Date.now(),
    name: "Brewed Coffee Dark Roast Skånerost",
    brand: "ZOÉGAS",
    description: "450 g",
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1734533714/cloud/417088/Bryggkaffe%20M%C3%B6rkrost%20Sk%C3%A5nerost.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/dryck/kaffe/bryggkaffe/bryggkaffe-morkrost-skanerost-7310731103011",
    price: 69.95,
    shortExpiryDate: false
  },
  {
    category: "Pantry",
    id: Date.now(),
    name: "Dessert Sauce Chocolate",
    brand: "O'hoj",
    description: "350 g",
    sale: { saleMessage: "30% off" },
    photoUrl: "https://res.cloudinary.com/coopsverige/images/e_sharpen,f_auto,fl_clip,fl_progressive,q_90,c_lpad,g_center,h_1000,w_1000/v1730462302/cloud/401520/Dessertsas%20Choklad.jpg",
    localProduced: false,
    link: "https://www.coop.se/handla/varor/skafferi/desserter/vaniljsas-dessertsas/dessertsas-choklad-8711327540903",
    price: 37.95,
    salePrice: 37.95 * 0.7,
    shortExpiryDate: false
  },
];
